### PR TITLE
Escape `@` and `&` in .env example to fix init scripts

### PR DESCRIPTION
**Pull request by boardend**

### CODE REVIEW

**Review by suricactus — APPROVED** [review]

**Comment by suricactus** [comment]
Very welcome first contribution! Since you are on this, it might be a good idea to add double quotes around all variables with `@` in their value too. It breaks on some shells. Feel free to do it here or in a follow-up PR.

I am also open to double quote all values.

**Review by faebebin — APPROVED** [review]
:partying_face:

**Comment by boardend** [comment]
No more unescaped `@` in `&` in `.env.example`

**Review by suricactus — APPROVED** [review]
Thanks a lot!

**Pull request merged**
