### PR TITLE
Rename error_origin 'container' to 'worker

### PR DESCRIPTION
**Pull request by faebebin**

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-2659 Investigate deeper the failed jobs](https://app.clickup.com/t/2192114/QF-2659)

**Comment by suricactus** [comment]
What is rationale behind this PR?

While the proposed naming is probably better, patching the JSONs for existing data is not realistic and having the two values just for the sake of clarity will make quering the database historically harder to write and memorize.

**Comment by faebebin** [comment]
Agree. Was only a naming initiative. But agree with your concerns

**Comment by faebebin** [comment]
-

**Pull request closed without merging**
