### PR TITLE
Catching exceptions earlier when trying to cancel orphans containers with empty references

### PR DESCRIPTION
**Pull request by why-not-try-calmer**
Please consider the associated ClickUp task for details.

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-3210 When listing orphaned containers, python-docker sometimes use empty references](https://app.clickup.com/t/2192114/QF-3210)

**Review by suricactus — APPROVED** [review]
Good catch!

**Comment by why-not-try-calmer** [comment]
Hum does it mean that indeed `NotFound` was raised, but not caught by the `except` clause? In which case I'd assume the import path I used is incorrectly?

**Comment by suricactus** [comment]
This is not deployed yet. IMO Sentry bot is just a bit stupid. Will try to deploy this week and we will see.

**Pull request merged**
