### PR TITLE
Make QGIS image name used by worker_wrapper as worker configurable

### PR DESCRIPTION
**Pull request by suricactus**
Allowed myself to clean a bit of unused references to the image name. Renamed the `QGIS_CONTAINER_NAME` to `QFIELDCLOUD_QGIS_IMAGE_NAME` cause this is the image, not the container and we should prefix all QFC specific variables with `QFIELDCLOUD_`.

Should replace #848 .

### CODE REVIEW

**Comment by dddpt** [comment]
With your fix, I get the following error
```
$ docker compose up -d --build --force-recreate
invalid interpolation format for services.worker_wrapper.environment.QFIELDCLOUD_QGIS_IMAGE_NAME: "${COMPOSE_PROJECT_NAME". You may need to escape any $ with another $
```
Fixed by setting double `$$` in the `docker-compose.yml`:  
```QFIELDCLOUD_QGIS_IMAGE_NAME: ${QFIELDCLOUD_QGIS_IMAGE_NAME:-$${COMPOSE_PROJECT_NAME}-qgis}```

Does it work on your side?

**Comment by suricactus** [comment]
Tried with bash and zsh, all works well here with the proposed solution. When I change it to your proposal I get:
```
*[QF-3717-test4][~/work/opengisch/qfieldcloud-private]$ grep QFIELDCLOUD_QGIS_IMAGE_NAME public/docker-compose.yml 
      QFIELDCLOUD_QGIS_IMAGE_NAME: ${QFIELDCLOUD_QGIS_IMAGE_NAME:-$${COMPOSE_PROJECT_NAME}-qgis}
*[QF-3717-test4][~/work/opengisch/qfieldcloud-private]$ docker compose exec worker_wrapper printenv | grep QFIELDCLOUD_QGIS_IMAGE_NAME         
QFIELDCLOUD_QGIS_IMAGE_NAME=${COMPOSE_PROJECT_NAME}-qgis
```

**Comment by dddpt** [comment]
OK... I am reinstalling docker as docker-CLI only.

It was a new docker install on this machine and I wanted to try out Docker Desktop to check out the GUI.
All the issues I have seem to stem from the fact my docker behaves weirdly. Let's go for a re-install.

I am coming back to you when this is done.

**Comment by dddpt** [comment]
Re-installation done. Your solution now works perfectly :ok_hand:

**Comment by suricactus** [comment]
Thanks for the update. Please finish the code review by giving green and we are ready to merge!

**Review by dddpt — APPROVED** [review]

**Comment by suricactus** [comment]
@dddpt most probably we broke the k8s setup, ping me these days to make it work again.

**Pull request merged**
