### PR TITLE
Make `AuthenticationFailed` errors just that instead of using `ValidationError`

### PR DESCRIPTION
**Pull request by suricactus**
Makes QFieldSync nicer:

| before | after |
|--|--|
| image | image |

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-3008 Make `AuthenticationFailed` errors just that instead of using `ValidationError`](https://app.clickup.com/t/2192114/QF-3008)

**Review by faebebin — APPROVED** [review]
LGTM

Tried it, cool :+1:

**Comment by why-not-try-calmer** [comment]
This is a very minor point, but I think the UX would be better if the message read

> Authentication failed

instead of

> [authentication_failed] Authentication failed

**Comment by suricactus** [comment]
@why-not-try-calmer It looks more scary indeed. However, showing the code helps a lot for internationalized UI. For me it's very hard to read the error on a screenshot if it is translated to chinese, but the code is something that is stable across translations.

**Pull request merged**
