### PR TITLE
Get the modified_pk from the feature even in transaction mode

### PR DESCRIPTION
**Pull request by suricactus**
Long story short, the layer.committedFeaturesAdded signal is not fired after layer.commitChanges() when in transaction mode. Have not looked further. If you already have ideas, more than welcome.

If the layer is using the QgsVectorLayerEditBuffer the commitedFeaturesAdded signal is fired.
But if transaction is used and the layer.editBuffer() returns QgsVectorLayerEditPasstrough, then there is no signal. The passtrough class is quite dull.

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-1478 Fix yet another error with 1) create 2) push 3) delete 4) push on app.qfield.cloud for FEFI](https://app.clickup.com/t/2192114/QF-1478)

**Review by m-kuhn — APPROVED** [review]

**Comment by m-kuhn** [comment]
Rebase, fix and use to test backport?

**Comment by suricactus** [comment]
This one needs a fix "upstream" in libqfieldsync.

**Comment by duke-nyuki** [comment]
The backport to `release` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release release
# Navigate to the new working tree
cd .worktrees/backport-release
# Create a new branch
git switch --create backport-180-to-release
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick eb7c6002d9b261e353126ddea2f083e89801af9a,af270f3bf2eaa99cb57158f3db48f9d1a56ee8fb,75a66e96f6dfabffe619f7a3cfcb44abf2435368,3f1f097021e66d08a35a42f185dbf330d2622a89,20512bf53a91c27a0d08b70bc8ff9ad52c531dc0,fd01d25eeb5b1951119fc11a4438dae4f7ab611a
# Push it to GitHub
git push --set-upstream origin backport-180-to-release
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release
```
Then, create a pull request where the `base` branch is `release` and the `compare`/`head` branch is `backport-180-to-release`.

**Comment by duke-nyuki** [comment]
The backport to `release` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release release
# Navigate to the new working tree
cd .worktrees/backport-release
# Create a new branch
git switch --create backport-180-to-release
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick eb7c6002d9b261e353126ddea2f083e89801af9a,af270f3bf2eaa99cb57158f3db48f9d1a56ee8fb,75a66e96f6dfabffe619f7a3cfcb44abf2435368,3f1f097021e66d08a35a42f185dbf330d2622a89,20512bf53a91c27a0d08b70bc8ff9ad52c531dc0,fd01d25eeb5b1951119fc11a4438dae4f7ab611a
# Push it to GitHub
git push --set-upstream origin backport-180-to-release
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release
```
Then, create a pull request where the `base` branch is `release` and the `compare`/`head` branch is `backport-180-to-release`.

**Comment by m-kuhn** [comment]
```

   1 file changed, 2 insertions(+)
  Auto-merging docker-qgis/entrypoint.py
  CONFLICT (content): Merge conflict in docker-qgis/entrypoint.py
  error: could not apply 20512bf... Rename vl_extent to vl_extent_wkt
  hint: After resolving the conflicts, mark them with
  hint: "git add/rm <pathspec>", then run
  hint: "git cherry-pick --continue".
  hint: You can instead skip this commit with "git cherry-pick --skip".
  hint: To abort and get back to the state before "git cherry-pick",
  hint: run "git cherry-pick --abort".
  /usr/bin/git cherry-pick --abort
  Error: Error: The process '/usr/bin/git' failed with exit code 1
```

**Comment by suricactus** [comment]
Would be great if the bot highlights which files had conflict in the comment :)

**Comment by duke-nyuki** [comment]
The backport to `release` failed:
```
The process '/usr/bin/git' failed with exit code 1
```
To backport manually, run these commands in your terminal:
```bash
# Fetch latest updates from GitHub
git fetch
# Create a new working tree
git worktree add .worktrees/backport-release release
# Navigate to the new working tree
cd .worktrees/backport-release
# Create a new branch
git switch --create backport-180-to-release
# Cherry-pick the merged commit of this pull request and resolve the conflicts
git cherry-pick eb7c6002d9b261e353126ddea2f083e89801af9a,af270f3bf2eaa99cb57158f3db48f9d1a56ee8fb,75a66e96f6dfabffe619f7a3cfcb44abf2435368,3f1f097021e66d08a35a42f185dbf330d2622a89,20512bf53a91c27a0d08b70bc8ff9ad52c531dc0,fd01d25eeb5b1951119fc11a4438dae4f7ab611a
# Push it to GitHub
git push --set-upstream origin backport-180-to-release
# Go back to the original working tree
cd ../..
# Delete the working tree
git worktree remove .worktrees/backport-release
```
Then, create a pull request where the `base` branch is `release` and the `compare`/`head` branch is `backport-180-to-release`.

**Pull request merged**
