### PR TITLE
Bump QFieldCloud SDK to 0.8.4

### PR DESCRIPTION
**Pull request by suricactus**
Prevents re-uploading of 8+MB files when they have not changed at all

Fix https://github.com/opengisch/QField/issues/5148#issuecomment-2090307608 and https://github.com/opengisch/QField/issues/5237#issuecomment-2111695728

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-3813 Basemaps uploaded multiple times after synchronization](https://app.clickup.com/t/2192114/QF-3813)

**Comment by idantene** [comment]
This is exciting @suricactus 🤩
Once merged (and relating to my original issue), will users have to update their app, or will this change take place only server-side, resolving the issue there?

**Comment by GiroDiGiiro** [comment]
Thank a lot for your responsiveness @suricactus !

**Review by boardend — APPROVED** [review]
Looks good to me

**Pull request merged**
