### PR TITLE
Ignore validation errors for sentry

### PR DESCRIPTION
**Pull request by m-kuhn**
Will ignore the number one "error" there is --> wrong login credentials provided.
I was wondering if we should only ignore exceptions that are unhandled (e.g. this one is handled, so it will still be hidden). @faebebin any idea?

### CODE REVIEW

**Comment by suricactus** [comment]
> I was wondering if we should only ignore exceptions that are unhandled (e.g. this one is handled, so it will still be hidden).

I think we should ignore exception that are handled if we want to solve the problem once and forever. However, explicitly listing them brings less magic, which is also not bad.

**Comment by m-kuhn** [comment]
The problem is, that currently we ignore the listed errors even if they are unhandled

**Comment by faebebin** [comment]
Yes I would agree here that the proper way would be to send all unhandled errors to sentry, except some special cases of orphaned workers. IMO good for now but maybe we could work out a proper solution -> ticket?

**Comment by m-kuhn** [comment]
There is a ticket we opened this morning in the current sprint ;-)

**Comment by faebebin** [comment]
Cool, thanks - I was not in the best shape yesterday ;)

**Pull request merged**
