### PR TITLE
Qf 2873 Add optional pagination to certain endpoints in the QFieldCloud API

### PR DESCRIPTION
**Pull request by why-not-try-calmer**

### CODE REVIEW

**Comment by duke-nyuki** [comment]
Task linked: [QF-2873 Add pagination to the QFC API endpoints](https://app.clickup.com/t/2192114/QF-2873)

**Review by suricactus — APPROVED** [review]
Thanks a lot. If you confirm each affected endpoint works wth a simple query for pagination, we are good to go.

**Comment by suricactus** [comment]
You can build a CURL request with the required token sent.

**Comment by why-not-try-calmer** [comment]
> You can build a CURL request with the required token sent.

But how to obtain the token?

**Comment by why-not-try-calmer** [comment]
Confirmed to be working:
- [ ] collaborators
- [ ] deltas
- [ ] jobs
- [ ] members
- [x] projects
- [x] users

**Pull request merged**
